name: Checkout tyk-pro

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  checkout_tyk_pro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@${{secrets.action_repo_commit_sha}} 

      - name: Checkout tyk-pro
        uses: TykTechnologies/github-actions/.github/actions/tests/checkout-tyk-pro@main
        with:
          org_gh_token: ${{ secrets.ORG_GH_TOKEN }}
